rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby
  - ruby-head
  - rbx-2.0

matrix:
  allow_failures:
    - rvm: rbx-2.0
    - rvm: jruby
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: ree
    - rvm: 1.9.2
